POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3NjIxNDM3NDksInVzZXJJZCI6MX0.Qc6JWDDWFuDik2UHm-IT3_jxSL6rHDlKUxWgUhTpqa0

{
    "name": "Test event",
    "description": "a test event",
    "location": "test location",
    "dateTime": "2025-10-22T12:00:00.000Z"
}