POST http://localhost:8080/events
content-type: application/json

{
    "name": "Test event",
    "description": "a test event",
    "location": "test location",
    "dateTime": "2025-10-22T12:00:00.000Z"
}