DELETE  http://localhost:8080/events/2
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3NjIxNDY4MDIsInVzZXJJZCI6MX0.zKZXRWpecl9q8HBpQf4OgFIMuAioyIvW17QylfY79AY