PUT  http://localhost:8080/events/1
content-type: application/json

{
    "name": "Updated test event",
    "description": "a test event",
    "location": "test location(updated!)",
    "dateTime": "2025-10-22T12:00:00Z"
}